import type { Metadata } from 'next';
import { Baskervville } from 'next/font/google';

import StyledComponentsRegistry from '@lib/StyledComponentsRegistry';
import RecoilRootWrapper from '@recoil/RecoilRootWrapper';

import Header from '@components/layout/Header';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import { StyledToastContainer } from '@lib/StyledToastContainer';

// const baskervville = Baskervville({ subsets: [''] });÷

export const metadata: Metadata = {
  title: 'Meubles',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <RecoilRootWrapper>
          <StyledComponentsRegistry>
            <Header />
            {children}
            <StyledToastContainer />
            {/* <ToastContainer /> */}
          </StyledComponentsRegistry>
        </RecoilRootWrapper>
      </body>
    </html>
  );
}
